name: TA-html-email
on:
  push:
    branches:
      - master
jobs:
  build-splunk-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: 5.x
      - name: Execute GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      - name: Install Go
        with:
          go-version: 1.17.3
        uses: actions/setup-go@v2
      - name: Compile darwin binary
        run: GOOS=darwin GOARCH=amd64 go build -o darwin_x86_64/bin/html-email
      - name: Compile linux binary
        run: GOOS=linux GOARCH=amd64 go build -o linux_x86_64/bin/html-email
      - name: Compile windows binary
        run: GOOS=windows GOARCH=amd64 go build -o windows_x86_64/bin/html-email.exe
      - name: Update version in app.conf
        run: sed -i "s/VERSION/$GITVERSION_SEMVER/g" default/app.conf
      - name: Create tgz artifact
        run: tar --transform 's|^|/TA-html-email/|' -czf "TA-html-email_$GITVERSION_SEMVER.tgz" appserver default metadata README static darwin_x86_64 linux_x86_64 windows_x86_64
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TA-html-email_${{ env.GITVERSION_SEMVER }}
          path: TA-html-email_${{ env.GITVERSION_SEMVER }}.tgz
          retention-days: 2
      - name: Create release
        uses: ncipollo/release-action@v1
        if: contains(github.event.head_commit.message, '; release')
        with:
          artifacts: TA-html-email_${{ env.GITVERSION_SEMVER }}.tgz
          bodyFile: release/release.md
          tag: v${{ env.GITVERSION_SEMVER }}
          token: ${{ secrets.GITHUB_TOKEN }}